# .github/workflows/build-deploy.yml

name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17 (OpenJDK)
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew bootJar

    - name: Transfer Jar to Remote Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }} # 원격 서버 IP 주소
        username: sungsin # 원격 서버 사용자 이름
        key: ${{ secrets.SERVER_KEY }} # 서버의 SSH 개인 키
        script: |
            ssh -i ${{ secrets.SERVER_KEY }} sungsin@${{ secrets.SERVER_HOST }} mkdir -p /home/sungsin/java_source
            scp -i ${{ secrets.SERVER_KEY }} ./build/libs/*.jar sungsin@${{ secrets.SERVER_HOST }}:/home/sungsin/java_source



