# .github/workflows/build-deploy.yml

name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17 (OpenJDK)
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Gradle Caching # Gradle 캐싱처리
      uses: actions/cache@v3
      with:
        path: |  
            ~/.gradle/caches
            ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
            ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew bootJar
  
    - name: Set jar file name as an environment variable
      run: |
        JAR_NAME=$(ls build/libs/*.jar | grep -o '[^/]*$')
        echo "JAR_NAME=$JAR_NAME" >> $GITHUB_ENV

    - name: Transfer Jar to Remote Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }} # 원격 서버 IP 주소
        username: sungsin # 원격 서버 사용자 이름
        key: ${{ secrets.SERVER_KEY }} # 서버의 SSH 개인 키
        source: "build/libs/*.jar"
        target: "/home/sungsin/java_source/"

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }} # 원격 서버 IP 주소
        username: sungsin
        key: ${{ secrets.SERVER_KEY }} # 서버의 SSH 개인 키
        port: 22
        script: |
          # 프로세스 확인 및 종료
          PID=$(lsof -t -i :8003)
          if [ -n "$PID" ]; then
            echo "프로세스 $PID를 종료합니다."
            kill $PID
            sleep 3
          fi

          # JAR 파일 실행
          JAR_PATH="/home/sungsin/java_source/build/libs/$JAR_NAME.jar"
          java -jar "$JAR_PATH" --spring.profiles.active=prod
          
          PID=$(lsof -t -i :8003)
          if [ -n "$PID" ]; then
            echo "jar 파일이 실행됐습니다."
          else
            echo "배포 실패: JAR 파일 실행 중 오류가 발생했습니다."
            exit 1
          fi
      



