# .github/workflows/build-deploy.yml

name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 'adopt@1.17'

    - name: Build with Gradle
      run: ./gradlew bootJar

    - name: Copy Jar to Remote Server
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.SERVER_HOST }} # 원격 서버 IP 주소
        username: sungsin # 원격 서버 사용자 이름
        key: ${{ secrets.SERVER_KEY }} # 서버의 SSH 개인 키
        source: 'build/app.jar' # 빌드된 jar 파일의 경로
        target: '/home/sungsin/java_source/app.jar' # 원격 서버에 복사될 경로

    - name: SSH Run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }} # 원격 서버 IP 주소
        username: sungsin # 원격 서버 사용자 이름
        key: ${{ secrets.SERVER_KEY }} # 서버의 SSH 개인 키
        script: 'java -jar /home/sungsin/java_source/app.jar' # 서버에서 실행될 스크립트
