# .github/workflows/build-deploy.yml

name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17 (OpenJDK)
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Gradle Caching # Gradle 캐싱처리
      uses: actions/cache@v3
      with:
        path: |  
            ~/.gradle/caches
            ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
            ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew bootJar

    - name: Deploy JAR and Script
      run: |
        mkdir -p deploy
        cp build/libs/AuthNexus-0.0.1-SNAPSHOT.jar deploy/ 
        cp createJar.sh deploy/

    - name: Run createJar.sh on Remote Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }} # 원격 서버 IP 주소
        username: ${{ secrets.SERVER_NAME }} # 원격 서버 사용자 이름
        key: ${{ secrets.SERVER_KEY }} # 서버의 SSH 개인 키
        port: 22
        script: |
          mkdir -p /home/devsung/java_source

    - name: Transfer Jar to Remote Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }} # 원격 서버 IP 주소
        username: ${{ secrets.SERVER_NAME }} # 원격 서버 사용자 이름
        key: ${{ secrets.SERVER_KEY }} # 서버의 SSH 개인 키
        source: "deploy/*"
        target: "/home/devsung/java_source/"
  
    - name: Run createJar.sh on Remote Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }} # 원격 서버 IP 주소
        username: ${{ secrets.SERVER_NAME }} # 원격 서버 사용자 이름
        key: ${{ secrets.SERVER_KEY }} # 서버의 SSH 개인 키
        port: 22
        script: |
          chmod +x /home/devsung/java_source/deploy/createJar.sh
          nohup bash /home/devsung/java_source/deploy/createJar.sh prod > /home/sungsin/java_source/deploy/AuthNexus.log 2>&1 &

          
