# .github/workflows/build-deploy.yml

name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17 (OpenJDK)
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew bootJar
        
    - name: Transfer Jar to Remote Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }} # 원격 서버 IP 주소
        username: sungsin # 원격 서버 사용자 이름
        key: ${{ secrets.SERVER_KEY }} # 서버의 SSH 개인 키
        source: "build/libs/*.jar"
        target: "/home/sungsin/java_source/"

    - name: Run Jar on Remote Server
      run: |
        bash createJar.sh prod
